sensors: 
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /airsim_node/drone_1/lidar/LidarCustom
    max_range: 100.0
    frame_subsample: 1
    point_subsample: 1
